In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("transfusion_5%.csv")

In [3]:
df

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
0                 2.0               50.0                12500.0   
1                 NaN               13.0                 3250.0   
2                 1.0               16.0                 4000.0   
3                 2.0                NaN                 5000.0   
4                 1.0               24.0                 6000.0   
..                ...                ...                    ...   
743               NaN                2.0                  500.0   
744              21.0                2.0                  500.0   
745              23.0                NaN                  750.0   
746              39.0                1.0                  250.0   
747              72.0                1.0                  250.0   

     Time (months)  whether he/she donated blood in March 2007  
0             98.0                                         1.0  
1              NaN                                         1.0  
2             35.0                                         1.0  
3             45.0                                         1.0  
4             77.0                                         0.0  
..             ...                                         ...  
743           38.0                                         0.0  
744           52.0                                         0.0  
745           62.0                                         0.0  
746           39.0                                         0.0  
747           72.0                                         0.0  

[748 rows x 5 columns]

In [4]:
df.dtypes

Recency (months)                              float64
Frequency (times)                             float64
Monetary (c.c. blood)                         float64
Time (months)                                 float64
whether he/she donated blood in March 2007    float64
dtype: object

In [5]:
df.isnull().sum()

Recency (months)                              46
Frequency (times)                             46
Monetary (c.c. blood)                         55
Time (months)                                 40
whether he/she donated blood in March 2007     0
dtype: int64

In [6]:
df.isnull().sum().sum()

187

In [7]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Recency (months)                              6.149733
Frequency (times)                             6.149733
Monetary (c.c. blood)                         7.352941
Time (months)                                 5.347594
whether he/she donated blood in March 2007    0.000000
dtype: float64

In [8]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase hilang :",null_percentages)

total nilai : 3740
nilai hilang : 187
persentase hilang : 5.0


In [9]:
df2 = df.fillna(df.mean())
df2

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
0            2.000000          50.000000                12500.0   
1            9.534188          13.000000                 3250.0   
2            1.000000          16.000000                 4000.0   
3            2.000000           5.561254                 5000.0   
4            1.000000          24.000000                 6000.0   
..                ...                ...                    ...   
743          9.534188           2.000000                  500.0   
744         21.000000           2.000000                  500.0   
745         23.000000           5.561254                  750.0   
746         39.000000           1.000000                  250.0   
747         72.000000           1.000000                  250.0   

     Time (months)  whether he/she donated blood in March 2007  
0        98.000000                                         1.0  
1        34.045198                                         1.0  
2        35.000000                                         1.0  
3        45.000000                                         1.0  
4        77.000000                                         0.0  
..             ...                                         ...  
743      38.000000                                         0.0  
744      52.000000                                         0.0  
745      62.000000                                         0.0  
746      39.000000                                         0.0  
747      72.000000                                         0.0  

[748 rows x 5 columns]

In [10]:
df2

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
0            2.000000          50.000000                12500.0   
1            9.534188          13.000000                 3250.0   
2            1.000000          16.000000                 4000.0   
3            2.000000           5.561254                 5000.0   
4            1.000000          24.000000                 6000.0   
..                ...                ...                    ...   
743          9.534188           2.000000                  500.0   
744         21.000000           2.000000                  500.0   
745         23.000000           5.561254                  750.0   
746         39.000000           1.000000                  250.0   
747         72.000000           1.000000                  250.0   

     Time (months)  whether he/she donated blood in March 2007  
0        98.000000                                         1.0  
1        34.045198                                         1.0  
2        35.000000                                         1.0  
3        45.000000                                         1.0  
4        77.000000                                         0.0  
..             ...                                         ...  
743      38.000000                                         0.0  
744      52.000000                                         0.0  
745      62.000000                                         0.0  
746      39.000000                                         0.0  
747      72.000000                                         0.0  

[748 rows x 5 columns]

In [12]:
df2.describe()

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
count        748.000000         748.000000             748.000000   
mean           9.534188           5.561254            1373.737374   
std            7.879164           5.751301            1408.796718   
min            0.000000           1.000000             250.000000   
25%            3.750000           2.000000             500.000000   
50%            9.267094           4.000000            1000.000000   
75%           14.000000           7.000000            1750.000000   
max           74.000000          50.000000           12500.000000   

       Time (months)  whether he/she donated blood in March 2007  
count     748.000000                                  748.000000  
mean       34.045198                                    0.237968  
std        23.439248                                    0.426124  
min         2.000000                                    0.000000  
25%        16.000000                                    0.000000  
50%        29.500000                                    0.000000  
75%        47.000000                                    0.000000  
max        98.000000                                    1.000000

# Klasifikasi

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [14]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [16]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[118  14]
 [ 42  13]]
0.7005347593582888


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [17]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[119  13]
 [ 42  13]]
0.7058823529411765


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [18]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[119  13]
 [ 41  14]]
0.7112299465240641


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [19]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[125   7]
 [ 42  13]]
0.7379679144385026


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
