In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("transfusion_10%.csv")

In [3]:
df

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
0                 2.0               50.0                    NaN   
1                 0.0               13.0                 3250.0   
2                 1.0               16.0                 4000.0   
3                 2.0               20.0                 5000.0   
4                 1.0               24.0                 6000.0   
..                ...                ...                    ...   
743              23.0                2.0                  500.0   
744               NaN                2.0                    NaN   
745               NaN                NaN                    NaN   
746              39.0                1.0                  250.0   
747              72.0                NaN                  250.0   

     Time (months)  whether he/she donated blood in March 2007  
0             98.0                                         1.0  
1             28.0                                         1.0  
2              NaN                                         1.0  
3             45.0                                         1.0  
4             77.0                                         0.0  
..             ...                                         ...  
743            NaN                                         0.0  
744           52.0                                         0.0  
745           62.0                                         0.0  
746            NaN                                         0.0  
747           72.0                                         0.0  

[748 rows x 5 columns]

In [4]:
df.dtypes

Recency (months)                              float64
Frequency (times)                             float64
Monetary (c.c. blood)                         float64
Time (months)                                 float64
whether he/she donated blood in March 2007    float64
dtype: object

In [5]:
df.isnull().sum()

Recency (months)                              107
Frequency (times)                              78
Monetary (c.c. blood)                          94
Time (months)                                  95
whether he/she donated blood in March 2007      0
dtype: int64

In [6]:
df.isnull().sum().sum()

374

In [7]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Recency (months)                              14.304813
Frequency (times)                             10.427807
Monetary (c.c. blood)                         12.566845
Time (months)                                 12.700535
whether he/she donated blood in March 2007     0.000000
dtype: float64

In [8]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase hilang :",null_percentages)

total nilai : 3740
nilai hilang : 374
persentase hilang : 10.0


In [9]:
df2 = df.fillna(df.mean())
df2

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
0            2.000000          50.000000            1399.847095   
1            0.000000          13.000000            3250.000000   
2            1.000000          16.000000            4000.000000   
3            2.000000          20.000000            5000.000000   
4            1.000000          24.000000            6000.000000   
..                ...                ...                    ...   
743         23.000000           2.000000             500.000000   
744          9.475819           2.000000            1399.847095   
745          9.475819           5.553731            1399.847095   
746         39.000000           1.000000             250.000000   
747         72.000000           5.553731             250.000000   

     Time (months)  whether he/she donated blood in March 2007  
0         98.00000                                         1.0  
1         28.00000                                         1.0  
2         35.20827                                         1.0  
3         45.00000                                         1.0  
4         77.00000                                         0.0  
..             ...                                         ...  
743       35.20827                                         0.0  
744       52.00000                                         0.0  
745       62.00000                                         0.0  
746       35.20827                                         0.0  
747       72.00000                                         0.0  

[748 rows x 5 columns]

In [10]:
df2

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
0            2.000000          50.000000            1399.847095   
1            0.000000          13.000000            3250.000000   
2            1.000000          16.000000            4000.000000   
3            2.000000          20.000000            5000.000000   
4            1.000000          24.000000            6000.000000   
..                ...                ...                    ...   
743         23.000000           2.000000             500.000000   
744          9.475819           2.000000            1399.847095   
745          9.475819           5.553731            1399.847095   
746         39.000000           1.000000             250.000000   
747         72.000000           5.553731             250.000000   

     Time (months)  whether he/she donated blood in March 2007  
0         98.00000                                         1.0  
1         28.00000                                         1.0  
2         35.20827                                         1.0  
3         45.00000                                         1.0  
4         77.00000                                         0.0  
..             ...                                         ...  
743       35.20827                                         0.0  
744       52.00000                                         0.0  
745       62.00000                                         0.0  
746       35.20827                                         0.0  
747       72.00000                                         0.0  

[748 rows x 5 columns]

In [11]:
df2.describe()

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
count        748.000000         748.000000             748.000000   
mean           9.475819           5.553731            1399.847095   
std            7.546542           5.704641            1322.465743   
min            0.000000           1.000000             250.000000   
25%            4.000000           2.000000             500.000000   
50%            9.475819           4.000000            1250.000000   
75%           14.000000           7.000000            1750.000000   
max           74.000000          50.000000           11500.000000   

       Time (months)  whether he/she donated blood in March 2007  
count     748.000000                                  748.000000  
mean       35.208270                                    0.237968  
std        23.068308                                    0.426124  
min         2.000000                                    0.000000  
25%        16.000000                                    0.000000  
50%        35.000000                                    0.000000  
75%        47.000000                                    0.000000  
max        98.000000                                    1.000000

# Klasifikasi

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [13]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=13)

In [15]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[119  14]
 [ 39  15]]
0.7165775401069518


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [16]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[117  16]
 [ 39  15]]
0.7058823529411765


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [17]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[119  14]
 [ 39  15]]
0.7165775401069518


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [18]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[117  16]
 [ 41  13]]
0.6951871657754011


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
