In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("onehr.csv")

In [3]:
df

date  WSR0  WSR1  WSR2  WSR3  WSR4  WSR5  WSR6  WSR7  WSR8  ...  \
0      1/1/1998   0.8   1.8   2.4   2.1   2.0   2.1   1.5   1.7   1.9  ...   
1      1/2/1998   2.8   3.2   3.3   2.7   3.3   3.2   2.9   2.8   3.1  ...   
2      1/3/1998   2.9   2.8   2.6   2.1   2.2   2.5   2.5   2.7   2.2  ...   
3      1/4/1998   4.7   3.8   3.7   3.8   2.9   3.1   2.8   2.5   2.4  ...   
4      1/5/1998   2.6   2.1   1.6   1.4   0.9   1.5   1.2   1.4   1.3  ...   
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
1094  1/10/2001   2.1   2.7   1.8   2.5   4.1   3.5   3.8   3.9   3.9  ...   
1095  1/11/2001   1.5   1.5   1.4   1.9   2.6   2.3   2.7   2.9   2.6  ...   
1096  1/12/2001   2.5   1.7   1.4   1.5   1.6   1.6   1.3   1.1   0.9  ...   
1097  1/13/2001   3.0   3.0   3.1   4.6   2.4   1.7   2.4   3.0   3.2  ...   
1098  1/14/2001   0.8   0.8   0.9   0.8   1.2   1.0   1.7   1.7   1.5  ...   

      RH50    U50    V50    HT50     KI    TT      SLP  SLP_  Precp  Class  
0     0.15  10.67  -1.56  5795.0 -12.10  17.9  10330.0 -55.0   0.00      0  
1     0.48   8.39   3.84  5805.0  14.05  29.0  10275.0 -55.0   0.00      0  
2     0.60   6.94   9.80  5790.0  17.90  41.3  10235.0 -40.0   0.00      0  
3     0.49   8.73  10.54  5775.0  31.15  51.7  10195.0 -40.0   2.08      0  
4      NaN    NaN    NaN     NaN    NaN   NaN      NaN   NaN   0.58      0  
...    ...    ...    ...     ...    ...   ...      ...   ...    ...    ...  
1094  0.48   9.48   5.72  5745.0 -18.60  13.1  10270.0  40.0   3.63      0  
1095  0.48  24.56  12.41  5710.0  15.20  41.5  10180.0 -90.0   0.00      0  
1096  0.02  23.19  -9.94  5770.0 -20.70  31.7  10210.0  30.0   0.00      0  
1097  0.56  18.23   3.95  5795.0 -29.50  16.9  10220.0  10.0   0.18      0  
1098  0.04  22.46   8.17  5775.0  21.30  45.4  10170.0 -50.0   0.03      0  

[1099 rows x 74 columns]

In [4]:
df.dtypes

date      object
WSR0     float64
WSR1     float64
WSR2     float64
WSR3     float64
          ...   
TT       float64
SLP      float64
SLP_     float64
Precp    float64
Class      int64
Length: 74, dtype: object

In [5]:
df.drop('date', axis=1, inplace=True)
df

WSR0  WSR1  WSR2  WSR3  WSR4  WSR5  WSR6  WSR7  WSR8  WSR9  ...  RH50  \
0      0.8   1.8   2.4   2.1   2.0   2.1   1.5   1.7   1.9   2.3  ...  0.15   
1      2.8   3.2   3.3   2.7   3.3   3.2   2.9   2.8   3.1   3.4  ...  0.48   
2      2.9   2.8   2.6   2.1   2.2   2.5   2.5   2.7   2.2   2.5  ...  0.60   
3      4.7   3.8   3.7   3.8   2.9   3.1   2.8   2.5   2.4   3.1  ...  0.49   
4      2.6   2.1   1.6   1.4   0.9   1.5   1.2   1.4   1.3   1.4  ...   NaN   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1094   2.1   2.7   1.8   2.5   4.1   3.5   3.8   3.9   3.9   3.4  ...  0.48   
1095   1.5   1.5   1.4   1.9   2.6   2.3   2.7   2.9   2.6   2.8  ...  0.48   
1096   2.5   1.7   1.4   1.5   1.6   1.6   1.3   1.1   0.9   1.2  ...  0.02   
1097   3.0   3.0   3.1   4.6   2.4   1.7   2.4   3.0   3.2   3.6  ...  0.56   
1098   0.8   0.8   0.9   0.8   1.2   1.0   1.7   1.7   1.5   2.6  ...  0.04   

        U50    V50    HT50     KI    TT      SLP  SLP_  Precp  Class  
0     10.67  -1.56  5795.0 -12.10  17.9  10330.0 -55.0   0.00      0  
1      8.39   3.84  5805.0  14.05  29.0  10275.0 -55.0   0.00      0  
2      6.94   9.80  5790.0  17.90  41.3  10235.0 -40.0   0.00      0  
3      8.73  10.54  5775.0  31.15  51.7  10195.0 -40.0   2.08      0  
4       NaN    NaN     NaN    NaN   NaN      NaN   NaN   0.58      0  
...     ...    ...     ...    ...   ...      ...   ...    ...    ...  
1094   9.48   5.72  5745.0 -18.60  13.1  10270.0  40.0   3.63      0  
1095  24.56  12.41  5710.0  15.20  41.5  10180.0 -90.0   0.00      0  
1096  23.19  -9.94  5770.0 -20.70  31.7  10210.0  30.0   0.00      0  
1097  18.23   3.95  5795.0 -29.50  16.9  10220.0  10.0   0.18      0  
1098  22.46   8.17  5775.0  21.30  45.4  10170.0 -50.0   0.03      0  

[1099 rows x 73 columns]

In [6]:
df.isnull().sum()

WSR0      27
WSR1      27
WSR2      28
WSR3      27
WSR4      27
        ... 
TT        76
SLP       61
SLP_     107
Precp      0
Class      0
Length: 73, dtype: int64

In [7]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

WSR0     2.456779
WSR1     2.456779
WSR2     2.547771
WSR3     2.456779
WSR4     2.456779
           ...   
TT       6.915378
SLP      5.550500
SLP_     9.736124
Precp    0.000000
Class    0.000000
Length: 73, dtype: float64

# Imputasi Median

In [9]:
dataset = df.fillna(df.median())
dataset

WSR0  WSR1  WSR2  WSR3  WSR4  WSR5  WSR6  WSR7  WSR8  WSR9  ...  RH50  \
0      0.8   1.8   2.4   2.1   2.0   2.1   1.5   1.7   1.9   2.3  ...  0.15   
1      2.8   3.2   3.3   2.7   3.3   3.2   2.9   2.8   3.1   3.4  ...  0.48   
2      2.9   2.8   2.6   2.1   2.2   2.5   2.5   2.7   2.2   2.5  ...  0.60   
3      4.7   3.8   3.7   3.8   2.9   3.1   2.8   2.5   2.4   3.1  ...  0.49   
4      2.6   2.1   1.6   1.4   0.9   1.5   1.2   1.4   1.3   1.4  ...  0.20   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1094   2.1   2.7   1.8   2.5   4.1   3.5   3.8   3.9   3.9   3.4  ...  0.48   
1095   1.5   1.5   1.4   1.9   2.6   2.3   2.7   2.9   2.6   2.8  ...  0.48   
1096   2.5   1.7   1.4   1.5   1.6   1.6   1.3   1.1   0.9   1.2  ...  0.02   
1097   3.0   3.0   3.1   4.6   2.4   1.7   2.4   3.0   3.2   3.6  ...  0.56   
1098   0.8   0.8   0.9   0.8   1.2   1.0   1.7   1.7   1.5   2.6  ...  0.04   

         U50    V50    HT50     KI    TT      SLP  SLP_  Precp  Class  
0     10.670  -1.56  5795.0 -12.10  17.9  10330.0 -55.0   0.00      0  
1      8.390   3.84  5805.0  14.05  29.0  10275.0 -55.0   0.00      0  
2      6.940   9.80  5790.0  17.90  41.3  10235.0 -40.0   0.00      0  
3      8.730  10.54  5775.0  31.15  51.7  10195.0 -40.0   2.08      0  
4      8.955  -0.21  5835.0  13.10  40.3  10160.0   0.0   0.58      0  
...      ...    ...     ...    ...   ...      ...   ...    ...    ...  
1094   9.480   5.72  5745.0 -18.60  13.1  10270.0  40.0   3.63      0  
1095  24.560  12.41  5710.0  15.20  41.5  10180.0 -90.0   0.00      0  
1096  23.190  -9.94  5770.0 -20.70  31.7  10210.0  30.0   0.00      0  
1097  18.230   3.95  5795.0 -29.50  16.9  10220.0  10.0   0.18      0  
1098  22.460   8.17  5775.0  21.30  45.4  10170.0 -50.0   0.03      0  

[1099 rows x 73 columns]

In [10]:
dataset.describe()

WSR0         WSR1         WSR2        WSR3         WSR4  \
count  1099.000000  1099.000000  1099.000000  1099.00000  1099.000000   
mean      1.737489     1.694359     1.640491     1.60737     1.602912   
std       1.302497     1.320148     1.285518     1.25483     1.232887   
min       0.000000     0.000000     0.000000     0.00000     0.000000   
25%       0.800000     0.700000     0.700000     0.60000     0.600000   
50%       1.400000     1.400000     1.300000     1.30000     1.300000   
75%       2.500000     2.500000     2.300000     2.20000     2.300000   
max       7.500000     7.700000     7.100000     7.30000     7.200000   

              WSR5         WSR6         WSR7         WSR8         WSR9  ...  \
count  1099.000000  1099.000000  1099.000000  1099.000000  1099.000000  ...   
mean      1.621292     1.717197     2.108007     2.603458     2.930209  ...   
std       1.218139     1.221992     1.202006     1.227273     1.234808  ...   
min       0.000000     0.000000     0.000000     0.100000     0.100000  ...   
25%       0.700000     0.800000     1.200000     1.700000     2.100000  ...   
50%       1.300000     1.500000     1.900000     2.500000     2.900000  ...   
75%       2.200000     2.300000     2.900000     3.400000     3.700000  ...   
max       7.400000     7.400000     7.500000     9.200000     8.500000  ...   

              RH50          U50          V50         HT50           KI  \
count  1099.000000  1099.000000  1099.000000  1099.000000  1099.000000   
mean      0.273558     9.760041     0.350237  5821.028207     9.275660   
std       0.229813     9.566879     7.120211    80.170516    19.846024   
min       0.010000   -14.920000   -22.480000  5480.000000   -53.600000   
25%       0.090000     2.760000    -3.430000  5770.000000    -3.700000   
50%       0.200000     8.955000    -0.210000  5835.000000    13.100000   
75%       0.420000    16.790000     3.485000  5885.000000    25.275000   
max       0.980000    41.360000    28.390000  5965.000000    42.050000   

                TT           SLP         SLP_        Precp        Class  
count  1099.000000   1099.000000  1099.000000  1099.000000  1099.000000  
mean     37.069518  10163.712466    -0.532302     0.302739     0.046406  
std      10.912719     51.676388    33.369019     1.102046     0.210458  
min     -10.100000   9995.000000  -135.000000     0.000000     0.000000  
25%      32.275000  10135.000000   -15.000000     0.000000     0.000000  
50%      40.300000  10160.000000     0.000000     0.000000     0.000000  
75%      44.275000  10190.000000    15.000000     0.030000     0.000000  
max      56.850000  10350.000000   140.000000    17.450000     1.000000  

[8 rows x 73 columns]

# Klasifikasi

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [12]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=5)

In [14]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [15]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[255   3]
 [ 14   3]]
0.9381818181818182


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [16]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[255   3]
 [ 16   1]]
0.9309090909090909


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [17]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[255   3]
 [ 17   0]]
0.9272727272727272


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [18]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[255   3]
 [ 17   0]]
0.9272727272727272


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [19]:
classifier = KNeighborsClassifier(n_neighbors=11, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


[[255   3]
 [ 16   1]]
0.9309090909090909
