In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("audit_10%.csv")

In [3]:
df

Sector_score  PARA_A  Score_A  Risk_A  PARA_B  Score_B  Risk_B  TOTAL  \
0            3.89    4.18      0.6   2.508    2.50      NaN   0.500   6.68   
1            3.89    0.00      NaN   0.000    4.83      NaN   0.966   4.83   
2            3.89    0.51      0.2   0.102    0.23      0.2   0.046   0.74   
3            3.89    0.00      0.2   0.000   10.80      0.6   6.480  10.80   
4            3.89    0.00      0.2   0.000    0.08      0.2   0.016   0.08   
..            ...     ...      ...     ...     ...      ...     ...    ...   
771           NaN     NaN      0.2     NaN    0.40      0.2   0.080   0.89   
772         55.57    0.47      0.2   0.094    0.37      NaN   0.074    NaN   
773         55.57    0.24      0.2     NaN     NaN      0.2   0.008   0.28   
774         55.57    0.20      NaN   0.040    0.00      0.2   0.000   0.20   
775         55.57    0.00      0.2   0.000    0.00      0.2   0.000   0.00   

     numbers  Score_B.1  ...  RiSk_E  History  Prob  Risk_F  Score  \
0        NaN        0.2  ...     0.4      NaN   0.2     0.0    2.4   
1        5.0        0.2  ...     0.4      0.0   0.2     0.0    2.0   
2        5.0        0.2  ...     0.4      0.0   0.2     0.0    2.0   
3        6.0        0.6  ...     0.4      0.0   0.2     0.0    4.4   
4        5.0        0.2  ...     0.4      0.0   NaN     0.0    NaN   
..       ...        ...  ...     ...      ...   ...     ...    ...   
771      5.0        0.2  ...     0.4      0.0   0.2     NaN    2.0   
772      5.0        0.2  ...     0.4      0.0   0.2     0.0    2.0   
773      5.0        0.2  ...     0.4      0.0   0.2     0.0    2.0   
774      5.0        NaN  ...     0.4      NaN   0.2     0.0    2.0   
775      5.0        NaN  ...     0.4      0.0   0.2     0.0    2.0   

     Inherent_Risk  CONTROL_RISK  Detection_Risk  Audit_Risk  Risk  
0            8.574           0.4             0.5      1.7148   1.0  
1            2.554           0.4             0.5      0.5108   0.0  
2            1.548           0.4             0.5      0.3096   0.0  
3           17.530           0.4             0.5      3.5060   1.0  
4            1.416           NaN             NaN      0.2832   0.0  
..             ...           ...             ...         ...   ...  
771          1.578           0.4             0.5      0.3156   0.0  
772          1.568           0.4             0.5         NaN   0.0  
773          1.456           0.4             0.5      0.2912   0.0  
774            NaN           0.4             0.5      0.2880   0.0  
775          1.464           0.4             0.5      0.2928   0.0  

[776 rows x 26 columns]

In [4]:
df.dtypes

Sector_score      float64
PARA_A            float64
Score_A           float64
Risk_A            float64
PARA_B            float64
Score_B           float64
Risk_B            float64
TOTAL             float64
numbers           float64
Score_B.1         float64
Risk_C            float64
Money_Value       float64
Score_MV          float64
Risk_D            float64
District_Loss     float64
PROB              float64
RiSk_E            float64
History           float64
Prob              float64
Risk_F            float64
Score             float64
Inherent_Risk     float64
CONTROL_RISK      float64
Detection_Risk    float64
Audit_Risk        float64
Risk              float64
dtype: object

In [5]:
df.isnull().sum()

Sector_score      74
PARA_A            62
Score_A           76
Risk_A            87
PARA_B            77
Score_B           83
Risk_B            93
TOTAL             94
numbers           88
Score_B.1         94
Risk_C            91
Money_Value       71
Score_MV          84
Risk_D            71
District_Loss     80
PROB              63
RiSk_E            93
History           73
Prob              89
Risk_F            80
Score             75
Inherent_Risk     71
CONTROL_RISK      92
Detection_Risk    75
Audit_Risk        81
Risk               0
dtype: int64

In [6]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Sector_score       9.536082
PARA_A             7.989691
Score_A            9.793814
Risk_A            11.211340
PARA_B             9.922680
Score_B           10.695876
Risk_B            11.984536
TOTAL             12.113402
numbers           11.340206
Score_B.1         12.113402
Risk_C            11.726804
Money_Value        9.149485
Score_MV          10.824742
Risk_D             9.149485
District_Loss     10.309278
PROB               8.118557
RiSk_E            11.984536
History            9.407216
Prob              11.469072
Risk_F            10.309278
Score              9.664948
Inherent_Risk      9.149485
CONTROL_RISK      11.855670
Detection_Risk     9.664948
Audit_Risk        10.438144
Risk               0.000000
dtype: float64

In [7]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase hilang :",null_percentages)

total nilai : 20176
nilai hilang : 2017
persentase hilang : 9.997026169706581


# Hapus Nilai Hilang

In [8]:
df2 = df.dropna(axis=0)
df2

Sector_score  PARA_A  Score_A  Risk_A  PARA_B  Score_B  Risk_B   TOTAL  \
23           3.89    0.94      0.2   0.188    0.01      0.2   0.002    0.95   
44           3.89    1.32      0.4   0.528    0.00      0.2   0.000    1.32   
45           3.89    0.00      0.2   0.000    1.03      0.2   0.206    1.03   
84           3.89    0.00      0.2   0.000    0.58      0.2   0.116    0.58   
129          3.41    3.34      0.6   2.004   37.59      0.6  22.554   40.93   
157          3.41   10.37      0.6   6.222  105.56      0.6  63.336  115.93   
170          3.41    1.18      0.4   0.472    0.00      0.2   0.000    1.18   
207          2.72    5.50      0.6   3.300   93.26      0.6  55.956   98.76   
218          2.72    6.02      0.6   3.612  135.69      0.6  81.414  141.71   
231          2.72    4.97      0.6   2.982   42.19      0.6  25.314   47.16   
260          2.72    1.05      0.4   0.420    0.00      0.2   0.000    1.05   
271          2.72    0.00      0.2   0.000    0.62      0.2   0.124    0.62   
290          2.37    2.22      0.6   1.332    3.40      0.6   2.040    5.62   
295          2.37    1.65      0.4   0.660    0.02      0.2   0.004    1.67   
321          2.37    1.27      0.4   0.508    1.01      0.4   0.404    2.28   
327          2.37    0.38      0.2   0.076    0.85      0.2   0.170    1.23   
340          2.37    0.90      0.2   0.180    0.29      0.2   0.058    1.19   
368          1.99    1.27      0.4   0.508    0.00      0.2   0.000    1.27   
377          1.99    1.23      0.4   0.492    0.00      0.2   0.000    1.23   
378          1.99    1.12      0.4   0.448    0.00      0.2   0.000    1.12   
380          1.99    0.77      0.2   0.154    0.00      0.2   0.000    0.77   
387          1.99    0.00      0.2   0.000    0.00      0.2   0.000    0.00   
398          1.85    0.95      0.2   0.190    0.00      0.2   0.000    0.95   
400          1.85    9.19      0.6   5.514    4.20      0.6   2.520   13.39   
427          1.85    2.89      0.6   1.734    0.11      0.2   0.022    3.00   
438          1.85    7.09      0.6   4.254    1.95      0.4   0.780    9.04   
444          1.85    3.74      0.6   2.244    0.55      0.2   0.110    4.29   
554         59.85    0.00      0.2   0.000    0.00      0.2   0.000    0.00   
569         59.85    0.39      0.2   0.078    0.39      0.2   0.078    0.78   
574         59.85    0.00      0.2   0.000    0.22      0.2   0.044    0.22   
606         55.57    1.49      0.4   0.596    2.34      0.6   1.404    3.83   
617         55.57    0.00      0.2   0.000    0.00      0.2   0.000    0.00   
624         55.57    0.00      0.2   0.000    0.00      0.2   0.000    0.00   
643         55.57    0.00      0.2   0.000    1.30      0.4   0.520    1.30   
680         55.57    0.21      0.2   0.042    0.00      0.2   0.000    0.21   
697         55.57    1.08      0.4   0.432    0.00      0.2   0.000    1.08   
706         55.57    0.76      0.2   0.152    0.00      0.2   0.000    0.76   
711         55.57    0.41      0.2   0.082    0.00      0.2   0.000    0.41   
731         55.57    0.70      0.2   0.140    0.79      0.2   0.158    1.49   
754         55.57    0.39      0.2   0.078    0.91      0.2   0.182    1.30   

     numbers  Score_B.1  ...  RiSk_E  History  Prob  Risk_F  Score  \
23       5.0        0.2  ...     0.4      0.0   0.2     0.0    2.0   
44       5.0        0.2  ...     0.4      0.0   0.2     0.0    2.2   
45       5.0        0.2  ...     0.4      0.0   0.2     0.0    2.0   
84       5.0        0.2  ...     0.4      0.0   0.2     0.0    2.0   
129      5.0        0.2  ...     0.4      0.0   0.2     0.0    4.0   
157      9.0        0.6  ...     0.4      0.0   0.2     0.0    4.8   
170      5.5        0.4  ...     0.8      0.0   0.2     0.0    3.2   
207      5.0        0.2  ...     0.4      0.0   0.2     0.0    4.0   
218      6.0        0.6  ...     0.8      0.0   0.2     0.0    5.0   
231      5.5        0.4  ...     0.4      0.0   0.2     0.0    4.

In [9]:
df2.describe()

Sector_score     PARA_A    Score_A     Risk_A      PARA_B    Score_B  \
count     40.000000  40.000000  40.000000  40.000000   40.000000  40.000000   
mean      20.142250   1.869750   0.350000   0.990550   10.871500   0.295000   
std       25.618157   2.548475   0.167944   1.580643   30.702579   0.163221   
min        1.850000   0.000000   0.200000   0.000000    0.000000   0.200000   
25%        2.275000   0.337500   0.200000   0.067500    0.000000   0.200000   
50%        3.065000   1.000000   0.300000   0.305000    0.255000   0.200000   
75%       55.570000   1.792500   0.450000   0.828000    1.097500   0.400000   
max       59.850000  10.370000   0.600000   6.222000  135.690000   0.600000   

          Risk_B       TOTAL    numbers  Score_B.1  ...     RiSk_E    History  \
count  40.000000   40.000000  40.000000  40.000000  ...  40.000000  40.000000   
mean    6.437900   12.741250   5.162500   0.235000  ...   0.490000   0.025000   
std    18.450272   32.442208   0.654251   0.100128  ...   0.247863   0.158114   
min     0.000000    0.000000   5.000000   0.200000  ...   0.400000   0.000000   
25%     0.000000    0.767500   5.000000   0.200000  ...   0.400000   0.000000   
50%     0.051000    1.210000   5.000000   0.200000  ...   0.400000   0.000000   
75%     0.433000    3.207500   5.000000   0.200000  ...   0.400000   0.000000   
max    81.414000  141.710000   9.000000   0.600000  ...   1.600000   1.000000   

            Prob     Risk_F      Score  Inherent_Risk  CONTROL_RISK  \
count  40.000000  40.000000  40.000000      40.000000      40.00000   
mean    0.205000   0.010000   2.630000      18.464850       0.50000   
std     0.031623   0.063246   0.862376      36.968025       0.25217   
min     0.200000   0.000000   2.000000       1.400000       0.40000   
25%     0.200000   0.000000   2.000000       1.643000       0.40000   
50%     0.200000   0.000000   2.200000       1.972000       0.40000   
75%     0.200000   0.000000   2.850000       4.424000       0.40000   
max     0.400000   0.400000   5.000000     143.210000       1.60000   

       Detection_Risk  Audit_Risk       Risk  
count            40.0   40.000000  40.000000  
mean              0.5    5.169460   0.300000  
std               0.0   12.060926   0.464095  
min               0.5    0.280000   0.000000  
25%               0.5    0.328600   0.000000  
50%               0.5    0.463400   0.000000  
75%               0.5    1.683800   1.000000  
max               0.5   57.284000   1.000000  

[8 rows x 26 columns]

# Klasifikasi

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [11]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [13]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [18]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[7 0]
 [2 1]]
0.8


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [19]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[7 0]
 [2 1]]
0.8


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [20]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[7 0]
 [3 0]]
0.7


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [21]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[7 0]
 [3 0]]
0.7


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
