In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("onehr.csv")

In [3]:
df

date  WSR0  WSR1  WSR2  WSR3  WSR4  WSR5  WSR6  WSR7  WSR8  ...  \
0      1/1/1998   0.8   1.8   2.4   2.1   2.0   2.1   1.5   1.7   1.9  ...   
1      1/2/1998   2.8   3.2   3.3   2.7   3.3   3.2   2.9   2.8   3.1  ...   
2      1/3/1998   2.9   2.8   2.6   2.1   2.2   2.5   2.5   2.7   2.2  ...   
3      1/4/1998   4.7   3.8   3.7   3.8   2.9   3.1   2.8   2.5   2.4  ...   
4      1/5/1998   2.6   2.1   1.6   1.4   0.9   1.5   1.2   1.4   1.3  ...   
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
1094  1/10/2001   2.1   2.7   1.8   2.5   4.1   3.5   3.8   3.9   3.9  ...   
1095  1/11/2001   1.5   1.5   1.4   1.9   2.6   2.3   2.7   2.9   2.6  ...   
1096  1/12/2001   2.5   1.7   1.4   1.5   1.6   1.6   1.3   1.1   0.9  ...   
1097  1/13/2001   3.0   3.0   3.1   4.6   2.4   1.7   2.4   3.0   3.2  ...   
1098  1/14/2001   0.8   0.8   0.9   0.8   1.2   1.0   1.7   1.7   1.5  ...   

      RH50    U50    V50    HT50     KI    TT      SLP  SLP_  Precp  Class  
0     0.15  10.67  -1.56  5795.0 -12.10  17.9  10330.0 -55.0   0.00      0  
1     0.48   8.39   3.84  5805.0  14.05  29.0  10275.0 -55.0   0.00      0  
2     0.60   6.94   9.80  5790.0  17.90  41.3  10235.0 -40.0   0.00      0  
3     0.49   8.73  10.54  5775.0  31.15  51.7  10195.0 -40.0   2.08      0  
4      NaN    NaN    NaN     NaN    NaN   NaN      NaN   NaN   0.58      0  
...    ...    ...    ...     ...    ...   ...      ...   ...    ...    ...  
1094  0.48   9.48   5.72  5745.0 -18.60  13.1  10270.0  40.0   3.63      0  
1095  0.48  24.56  12.41  5710.0  15.20  41.5  10180.0 -90.0   0.00      0  
1096  0.02  23.19  -9.94  5770.0 -20.70  31.7  10210.0  30.0   0.00      0  
1097  0.56  18.23   3.95  5795.0 -29.50  16.9  10220.0  10.0   0.18      0  
1098  0.04  22.46   8.17  5775.0  21.30  45.4  10170.0 -50.0   0.03      0  

[1099 rows x 74 columns]

In [4]:
df.dtypes

date      object
WSR0     float64
WSR1     float64
WSR2     float64
WSR3     float64
          ...   
TT       float64
SLP      float64
SLP_     float64
Precp    float64
Class      int64
Length: 74, dtype: object

In [5]:
df.drop('date', axis=1, inplace=True)
df

WSR0  WSR1  WSR2  WSR3  WSR4  WSR5  WSR6  WSR7  WSR8  WSR9  ...  RH50  \
0      0.8   1.8   2.4   2.1   2.0   2.1   1.5   1.7   1.9   2.3  ...  0.15   
1      2.8   3.2   3.3   2.7   3.3   3.2   2.9   2.8   3.1   3.4  ...  0.48   
2      2.9   2.8   2.6   2.1   2.2   2.5   2.5   2.7   2.2   2.5  ...  0.60   
3      4.7   3.8   3.7   3.8   2.9   3.1   2.8   2.5   2.4   3.1  ...  0.49   
4      2.6   2.1   1.6   1.4   0.9   1.5   1.2   1.4   1.3   1.4  ...   NaN   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1094   2.1   2.7   1.8   2.5   4.1   3.5   3.8   3.9   3.9   3.4  ...  0.48   
1095   1.5   1.5   1.4   1.9   2.6   2.3   2.7   2.9   2.6   2.8  ...  0.48   
1096   2.5   1.7   1.4   1.5   1.6   1.6   1.3   1.1   0.9   1.2  ...  0.02   
1097   3.0   3.0   3.1   4.6   2.4   1.7   2.4   3.0   3.2   3.6  ...  0.56   
1098   0.8   0.8   0.9   0.8   1.2   1.0   1.7   1.7   1.5   2.6  ...  0.04   

        U50    V50    HT50     KI    TT      SLP  SLP_  Precp  Class  
0     10.67  -1.56  5795.0 -12.10  17.9  10330.0 -55.0   0.00      0  
1      8.39   3.84  5805.0  14.05  29.0  10275.0 -55.0   0.00      0  
2      6.94   9.80  5790.0  17.90  41.3  10235.0 -40.0   0.00      0  
3      8.73  10.54  5775.0  31.15  51.7  10195.0 -40.0   2.08      0  
4       NaN    NaN     NaN    NaN   NaN      NaN   NaN   0.58      0  
...     ...    ...     ...    ...   ...      ...   ...    ...    ...  
1094   9.48   5.72  5745.0 -18.60  13.1  10270.0  40.0   3.63      0  
1095  24.56  12.41  5710.0  15.20  41.5  10180.0 -90.0   0.00      0  
1096  23.19  -9.94  5770.0 -20.70  31.7  10210.0  30.0   0.00      0  
1097  18.23   3.95  5795.0 -29.50  16.9  10220.0  10.0   0.18      0  
1098  22.46   8.17  5775.0  21.30  45.4  10170.0 -50.0   0.03      0  

[1099 rows x 73 columns]

In [6]:
df.isnull().sum()

WSR0      27
WSR1      27
WSR2      28
WSR3      27
WSR4      27
        ... 
TT        76
SLP       61
SLP_     107
Precp      0
Class      0
Length: 73, dtype: int64

In [7]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

WSR0     2.456779
WSR1     2.456779
WSR2     2.547771
WSR3     2.456779
WSR4     2.456779
           ...   
TT       6.915378
SLP      5.550500
SLP_     9.736124
Precp    0.000000
Class    0.000000
Length: 73, dtype: float64

# Imputasi Mean

In [8]:
dataset = df.fillna(df.mean())
dataset

WSR0  WSR1  WSR2  WSR3  WSR4  WSR5  WSR6  WSR7  WSR8  WSR9  ...  \
0      0.8   1.8   2.4   2.1   2.0   2.1   1.5   1.7   1.9   2.3  ...   
1      2.8   3.2   3.3   2.7   3.3   3.2   2.9   2.8   3.1   3.4  ...   
2      2.9   2.8   2.6   2.1   2.2   2.5   2.5   2.7   2.2   2.5  ...   
3      4.7   3.8   3.7   3.8   2.9   3.1   2.8   2.5   2.4   3.1  ...   
4      2.6   2.1   1.6   1.4   0.9   1.5   1.2   1.4   1.3   1.4  ...   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
1094   2.1   2.7   1.8   2.5   4.1   3.5   3.8   3.9   3.9   3.4  ...   
1095   1.5   1.5   1.4   1.9   2.6   2.3   2.7   2.9   2.6   2.8  ...   
1096   2.5   1.7   1.4   1.5   1.6   1.6   1.3   1.1   0.9   1.2  ...   
1097   3.0   3.0   3.1   4.6   2.4   1.7   2.4   3.0   3.2   3.6  ...   
1098   0.8   0.8   0.9   0.8   1.2   1.0   1.7   1.7   1.5   2.6  ...   

          RH50       U50        V50         HT50         KI         TT  \
0     0.150000  10.67000  -1.560000  5795.000000 -12.100000  17.900000   
1     0.480000   8.39000   3.840000  5805.000000  14.050000  29.000000   
2     0.600000   6.94000   9.800000  5790.000000  17.900000  41.300000   
3     0.490000   8.73000  10.540000  5775.000000  31.150000  51.700000   
4     0.278945   9.84508   0.409416  5820.019512   8.975417  36.829521   
...        ...       ...        ...          ...        ...        ...   
1094  0.480000   9.48000   5.720000  5745.000000 -18.600000  13.100000   
1095  0.480000  24.56000  12.410000  5710.000000  15.200000  41.500000   
1096  0.020000  23.19000  -9.940000  5770.000000 -20.700000  31.700000   
1097  0.560000  18.23000   3.950000  5795.000000 -29.500000  16.900000   
1098  0.040000  22.46000   8.170000  5775.000000  21.300000  45.400000   

               SLP       SLP_  Precp  Class  
0     10330.000000 -55.000000   0.00      0  
1     10275.000000 -55.000000   0.00      0  
2     10235.000000 -40.000000   0.00      0  
3     10195.000000 -40.000000   2.08      0  
4     10163.930636  -0.589718   0.58      0  
...            ...        ...    ...    ...  
1094  10270.000000  40.000000   3.63      0  
1095  10180.000000 -90.000000   0.00      0  
1096  10210.000000  30.000000   0.00      0  
1097  10220.000000  10.000000   0.18      0  
1098  10170.000000 -50.000000   0.03      0  

[1099 rows x 73 columns]

In [9]:
dataset.describe()

WSR0         WSR1         WSR2         WSR3         WSR4  \
count  1099.000000  1099.000000  1099.000000  1099.000000  1099.000000   
mean      1.745989     1.701772     1.649393     1.615112     1.610541   
std       1.301394     1.319321     1.284338     1.253881     1.231948   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.800000     0.700000     0.700000     0.600000     0.600000   
50%       1.500000     1.400000     1.300000     1.300000     1.400000   
75%       2.500000     2.500000     2.300000     2.200000     2.300000   
max       7.500000     7.700000     7.100000     7.300000     7.200000   

              WSR5         WSR6         WSR7         WSR8         WSR9  ...  \
count  1099.000000  1099.000000  1099.000000  1099.000000  1099.000000  ...   
mean      1.629384     1.722460     2.112454     2.605767     2.930912  ...   
std       1.217071     1.221524     1.201620     1.227176     1.234800  ...   
min       0.000000     0.000000     0.000000     0.100000     0.100000  ...   
25%       0.700000     0.800000     1.200000     1.700000     2.100000  ...   
50%       1.400000     1.500000     2.000000     2.500000     2.900000  ...   
75%       2.200000     2.300000     2.900000     3.400000     3.700000  ...   
max       7.400000     7.400000     7.500000     9.200000     8.500000  ...   

              RH50          U50          V50         HT50           KI  \
count  1099.000000  1099.000000  1099.000000  1099.000000  1099.000000   
mean      0.278945     9.845080     0.409416  5820.019512     8.975417   
std       0.228948     9.563298     7.117881    80.082492    19.817048   
min       0.010000   -14.920000   -22.480000  5480.000000   -53.600000   
25%       0.090000     2.760000    -3.430000  5770.000000    -3.700000   
50%       0.220000     9.845080     0.409416  5825.000000    10.350000   
75%       0.420000    16.790000     3.485000  5885.000000    25.275000   
max       0.980000    41.360000    28.390000  5965.000000    42.050000   

                TT           SLP         SLP_        Precp        Class  
count  1099.000000   1099.000000  1099.000000  1099.000000  1099.000000  
mean     36.829521  10163.930636    -0.589718     0.302739     0.046406  
std      10.877105     51.668544    33.368561     1.102046     0.210458  
min     -10.100000   9995.000000  -135.000000     0.000000     0.000000  
25%      32.275000  10135.000000   -15.000000     0.000000     0.000000  
50%      39.500000  10160.000000    -0.589718     0.000000     0.000000  
75%      44.275000  10190.000000    15.000000     0.030000     0.000000  
max      56.850000  10350.000000   140.000000    17.450000     1.000000  

[8 rows x 73 columns]

# Klasifikasi

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [11]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=6)

In [13]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
classifier = DecisionTreeClassifier(max_depth=3)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[255   4]
 [ 16   0]]
0.9272727272727272


In [15]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[194  65]
 [  3  13]]
0.7527272727272727


In [16]:
classifier = MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[250   9]
 [ 12   4]]
0.9236363636363636
