In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("hepatitis.csv")

In [3]:
df

age  sex  steroid  antivirals  fatigue  malaise  anorexia  liver_big  \
0     30    2      1.0           2      2.0      2.0       2.0        1.0   
1     50    1      1.0           2      1.0      2.0       2.0        1.0   
2     78    1      2.0           2      1.0      2.0       2.0        2.0   
3     31    1      NaN           1      2.0      2.0       2.0        2.0   
4     34    1      2.0           2      2.0      2.0       2.0        2.0   
..   ...  ...      ...         ...      ...      ...       ...        ...   
150   46    1      2.0           2      1.0      1.0       1.0        2.0   
151   44    1      2.0           2      1.0      2.0       2.0        2.0   
152   61    1      1.0           2      1.0      1.0       2.0        1.0   
153   53    2      1.0           2      1.0      2.0       2.0        2.0   
154   43    1      2.0           2      1.0      2.0       2.0        2.0   

     liver_firm  spleen_palpable  spiders  ascites  varices  bilirubin  \
0           2.0              2.0      2.0      2.0      2.0        1.0   
1           2.0              2.0      2.0      2.0      2.0        0.9   
2           2.0              2.0      2.0      2.0      2.0        0.7   
3           2.0              2.0      2.0      2.0      2.0        0.7   
4           2.0              2.0      2.0      2.0      2.0        1.0   
..          ...              ...      ...      ...      ...        ...   
150         2.0              2.0      1.0      1.0      1.0        7.6   
151         1.0              2.0      2.0      2.0      2.0        0.9   
152         1.0              2.0      1.0      2.0      2.0        0.8   
153         2.0              1.0      1.0      2.0      1.0        1.5   
154         2.0              1.0      1.0      1.0      2.0        1.2   

     alk_phosphate   sgot  albumin  protime  histology  class  
0             85.0   18.0      4.0      NaN          1      2  
1            135.0   42.0      3.5      NaN          1      2  
2             96.0   32.0      4.0      NaN          1      2  
3             46.0   52.0      4.0     80.0          1      2  
4              NaN  200.0      4.0      NaN          1      2  
..             ...    ...      ...      ...        ...    ...  
150            NaN  242.0      3.3     50.0          2      1  
151          126.0  142.0      4.3      NaN          2      2  
152           75.0   20.0      4.1      NaN          2      2  
153           81.0   19.0      4.1     48.0          2      2  
154          100.0   19.0      3.1     42.0          2      1  

[155 rows x 20 columns]

In [4]:
df.dtypes

age                  int64
sex                  int64
steroid            float64
antivirals           int64
fatigue            float64
malaise            float64
anorexia           float64
liver_big          float64
liver_firm         float64
spleen_palpable    float64
spiders            float64
ascites            float64
varices            float64
bilirubin          float64
alk_phosphate      float64
sgot               float64
albumin            float64
protime            float64
histology            int64
class                int64
dtype: object

In [5]:
df.isnull().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64

In [6]:
df.isnull().sum().sum()

167

In [7]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

age                 0.000000
sex                 0.000000
steroid             0.645161
antivirals          0.000000
fatigue             0.645161
malaise             0.645161
anorexia            0.645161
liver_big           6.451613
liver_firm          7.096774
spleen_palpable     3.225806
spiders             3.225806
ascites             3.225806
varices             3.225806
bilirubin           3.870968
alk_phosphate      18.709677
sgot                2.580645
albumin            10.322581
protime            43.225806
histology           0.000000
class               0.000000
dtype: float64

In [8]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase hilang :",null_percentages)

total nilai : 3100
nilai hilang : 167
persentase hilang : 5.387096774193548


In [9]:
df2 = df.fillna(df.mean())
df2

age  sex   steroid  antivirals  fatigue  malaise  anorexia  liver_big  \
0     30    2  1.000000           2      2.0      2.0       2.0        1.0   
1     50    1  1.000000           2      1.0      2.0       2.0        1.0   
2     78    1  2.000000           2      1.0      2.0       2.0        2.0   
3     31    1  1.506494           1      2.0      2.0       2.0        2.0   
4     34    1  2.000000           2      2.0      2.0       2.0        2.0   
..   ...  ...       ...         ...      ...      ...       ...        ...   
150   46    1  2.000000           2      1.0      1.0       1.0        2.0   
151   44    1  2.000000           2      1.0      2.0       2.0        2.0   
152   61    1  1.000000           2      1.0      1.0       2.0        1.0   
153   53    2  1.000000           2      1.0      2.0       2.0        2.0   
154   43    1  2.000000           2      1.0      2.0       2.0        2.0   

     liver_firm  spleen_palpable  spiders  ascites  varices  bilirubin  \
0           2.0              2.0      2.0      2.0      2.0        1.0   
1           2.0              2.0      2.0      2.0      2.0        0.9   
2           2.0              2.0      2.0      2.0      2.0        0.7   
3           2.0              2.0      2.0      2.0      2.0        0.7   
4           2.0              2.0      2.0      2.0      2.0        1.0   
..          ...              ...      ...      ...      ...        ...   
150         2.0              2.0      1.0      1.0      1.0        7.6   
151         1.0              2.0      2.0      2.0      2.0        0.9   
152         1.0              2.0      1.0      2.0      2.0        0.8   
153         2.0              1.0      1.0      2.0      1.0        1.5   
154         2.0              1.0      1.0      1.0      2.0        1.2   

     alk_phosphate   sgot  albumin    protime  histology  class  
0        85.000000   18.0      4.0  61.852273          1      2  
1       135.000000   42.0      3.5  61.852273          1      2  
2        96.000000   32.0      4.0  61.852273          1      2  
3        46.000000   52.0      4.0  80.000000          1      2  
4       105.325397  200.0      4.0  61.852273          1      2  
..             ...    ...      ...        ...        ...    ...  
150     105.325397  242.0      3.3  50.000000          2      1  
151     126.000000  142.0      4.3  61.852273          2      2  
152      75.000000   20.0      4.1  61.852273          2      2  
153      81.000000   19.0      4.1  48.000000          2      2  
154     100.000000   19.0      3.1  42.000000          2      1  

[155 rows x 20 columns]

In [10]:
df2

age  sex   steroid  antivirals  fatigue  malaise  anorexia  liver_big  \
0     30    2  1.000000           2      2.0      2.0       2.0        1.0   
1     50    1  1.000000           2      1.0      2.0       2.0        1.0   
2     78    1  2.000000           2      1.0      2.0       2.0        2.0   
3     31    1  1.506494           1      2.0      2.0       2.0        2.0   
4     34    1  2.000000           2      2.0      2.0       2.0        2.0   
..   ...  ...       ...         ...      ...      ...       ...        ...   
150   46    1  2.000000           2      1.0      1.0       1.0        2.0   
151   44    1  2.000000           2      1.0      2.0       2.0        2.0   
152   61    1  1.000000           2      1.0      1.0       2.0        1.0   
153   53    2  1.000000           2      1.0      2.0       2.0        2.0   
154   43    1  2.000000           2      1.0      2.0       2.0        2.0   

     liver_firm  spleen_palpable  spiders  ascites  varices  bilirubin  \
0           2.0              2.0      2.0      2.0      2.0        1.0   
1           2.0              2.0      2.0      2.0      2.0        0.9   
2           2.0              2.0      2.0      2.0      2.0        0.7   
3           2.0              2.0      2.0      2.0      2.0        0.7   
4           2.0              2.0      2.0      2.0      2.0        1.0   
..          ...              ...      ...      ...      ...        ...   
150         2.0              2.0      1.0      1.0      1.0        7.6   
151         1.0              2.0      2.0      2.0      2.0        0.9   
152         1.0              2.0      1.0      2.0      2.0        0.8   
153         2.0              1.0      1.0      2.0      1.0        1.5   
154         2.0              1.0      1.0      1.0      2.0        1.2   

     alk_phosphate   sgot  albumin    protime  histology  class  
0        85.000000   18.0      4.0  61.852273          1      2  
1       135.000000   42.0      3.5  61.852273          1      2  
2        96.000000   32.0      4.0  61.852273          1      2  
3        46.000000   52.0      4.0  80.000000          1      2  
4       105.325397  200.0      4.0  61.852273          1      2  
..             ...    ...      ...        ...        ...    ...  
150     105.325397  242.0      3.3  50.000000          2      1  
151     126.000000  142.0      4.3  61.852273          2      2  
152      75.000000   20.0      4.1  61.852273          2      2  
153      81.000000   19.0      4.1  48.000000          2      2  
154     100.000000   19.0      3.1  42.000000          2      1  

[155 rows x 20 columns]

In [11]:
df2.isnull().sum()

age                0
sex                0
steroid            0
antivirals         0
fatigue            0
malaise            0
anorexia           0
liver_big          0
liver_firm         0
spleen_palpable    0
spiders            0
ascites            0
varices            0
bilirubin          0
alk_phosphate      0
sgot               0
albumin            0
protime            0
histology          0
class              0
dtype: int64

In [12]:
df2.describe()

age         sex     steroid  antivirals     fatigue     malaise  \
count  155.000000  155.000000  155.000000  155.000000  155.000000  155.000000   
mean    41.200000    1.103226    1.506494    1.845161    1.350649    1.603896   
std     12.565878    0.305240    0.499958    0.362923    0.477173    0.489086   
min      7.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%     32.000000    1.000000    1.000000    2.000000    1.000000    1.000000   
50%     39.000000    1.000000    2.000000    2.000000    1.000000    2.000000   
75%     50.000000    1.000000    2.000000    2.000000    2.000000    2.000000   
max     78.000000    2.000000    2.000000    2.000000    2.000000    2.000000   

         anorexia   liver_big  liver_firm  spleen_palpable     spiders  \
count  155.000000  155.000000  155.000000       155.000000  155.000000   
mean     1.792208    1.827586    1.583333         1.800000    1.660000   
std      0.405727    0.366536    0.476731         0.394771    0.467516   
min      1.000000    1.000000    1.000000         1.000000    1.000000   
25%      2.000000    2.000000    1.000000         2.000000    1.000000   
50%      2.000000    2.000000    2.000000         2.000000    2.000000   
75%      2.000000    2.000000    2.000000         2.000000    2.000000   
max      2.000000    2.000000    2.000000         2.000000    2.000000   

          ascites     varices   bilirubin  alk_phosphate        sgot  \
count  155.000000  155.000000  155.000000     155.000000  155.000000   
mean     1.866667    1.880000    1.427517     105.325397   85.894040   
std      0.335491    0.320713    1.188301      46.405585   88.478932   
min      1.000000    1.000000    0.300000      26.000000   14.000000   
25%      2.000000    2.000000    0.800000      78.000000   32.500000   
50%      2.000000    2.000000    1.000000     102.000000   59.000000   
75%      2.000000    2.000000    1.500000     119.500000   99.000000   
max      2.000000    2.000000    8.000000     295.000000  648.000000   

          albumin     protime   histology       class  
count  155.000000  155.000000  155.000000  155.000000  
mean     3.817266   61.852273    1.451613    1.793548  
std      0.616750   17.193528    0.499266    0.406070  
min      2.100000    0.000000    1.000000    1.000000  
25%      3.500000   57.000000    1.000000    2.000000  
50%      3.900000   61.852273    1.000000    2.000000  
75%      4.200000   65.000000    2.000000    2.000000  
max      6.400000  100.000000    2.000000    2.000000

# Klasifikasi

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [14]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [16]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[ 2  8]
 [ 5 24]]
0.6666666666666666


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [17]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[ 1  9]
 [ 2 27]]
0.717948717948718


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [18]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[ 0 10]
 [ 0 29]]
0.7435897435897436


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [19]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[ 0 10]
 [ 0 29]]
0.7435897435897436


C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
